### ISSUE TITLE
warning of node.js 12 deprecation

### ISSUE THREAD

**Issue by davidfilat** [ViRGiL175/github-check-branch-fast-forward-ness#2]
I start getting a warning from Github that the action should be updated to node 16. 
Are there any plans for updating the action?
<img width="1329" alt="CleanShot 2022-11-01 at 22 19 23@2x" src="https://user-images.githubusercontent.com/1475163/199333081-05747615-435e-4416-aaa8-2c21ca1c7186.png">

**Comment by ViRGiL175** [comment]
> I start getting a warning from Github that the action should be updated to node 16. Are there any plans for updating the action? <img alt="CleanShot 2022-11-01 at 22 19 23@2x" width="1329" src="https://user-images.githubusercontent.com/1475163/199333081-05747615-435e-4416-aaa8-2c21ca1c7186.png">

Hi. 

This action works completely via `bash` and `git`. It doesn't have Node dependencies and do not require it. Pure shell commands:

https://github.com/ViRGiL175/github-check-branch-fast-forward-ness/blob/8ca99eec7eba240295f2ce0e414bc048a6801591/action.yml#L15-L34

Maybe you habitually added Node 12 requirement to your `.yml` action config? 

If so, you can delete any Node requirements. 

Check out my example action setup: https://github.com/ViRGiL175/github-check-branch-fast-forward-ness#how-can-i-use-it

**Comment by ViRGiL175** [comment]
> I start getting a warning from Github that the action should be updated to node 16. Are there any plans for updating the action? <img alt="CleanShot 2022-11-01 at 22 19 23@2x" width="1329" src="https://user-images.githubusercontent.com/1475163/199333081-05747615-435e-4416-aaa8-2c21ca1c7186.png">

Also I tried to find any lookalike warnings in my repositories and didn't find nothing.

Maybe I don't know where to look. Is it action running log?

**Comment by davidfilat** [comment]
found the issue. I was using checkout@v3. Maybe you could update the README 

Thank you @ViRGiL175

**Comment by ViRGiL175** [comment]
Sorry, but I'm using v3 checkout on a few of my repositories too. And I didn't see any warnings. 

Maybe there is some other dependency that causes this warning. I can't say.
